steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/swift-surf-368719/flaskhelloworldapp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/swift-surf-368719/flaskhelloworldapp']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'swift-surf-368719', '--image', 'gcr.io/swift-surf-368719/flaskhelloworldapp', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/swift-surf-368719/flaskhelloworldapp